### ISSUE TITLE
Problem with connection to mysql when using Blacklist strategy

### ISSUE THREAD

**Issue by rpiotrow** [sunitparekh/data-anonymization#24]
Hi,

I have installed ruby and data-anonymization with this commands:
```
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.2
sudo apt-get install ruby2.2-dev
sudo gem install data-anonymization
sudo apt-get install libmysqlclient-dev
sudo gem install mysql
```

I have a test script test.rb:
```
require 'data-anonymization'

DataAnon::Utils::Logging.logger.level = Logger::DEBUG

database 'test' do
	strategy DataAnon::Strategy::Blacklist
	source_db :adapter => 'mysql', :host => 'localhost', :port => 3306, :pool => 5, :username => 'root', :password => 'mysql', :database => 'test'

	table 'user' do
		primary_key 'id'

		anonymize('email').using FieldStrategy::RandomEmail.new('test','com')
	end

end
```

and I run it like this:
```
ruby test.rb
```

I get this error in output:
```
D, [2015-03-03T11:41:49.556618 #14749] DEBUG -- : Processing Database: adservice
D, [2015-03-03T11:41:49.556796 #14749] DEBUG -- : Processing table user with fields strategies {"email"=>#<DataAnon::Strategy::Field::RandomEmail:0x00000003254d08 @hostname="test", @tld="com">}
E, [2015-03-03T11:41:49.584712 #14749] ERROR -- : 
No connection pool for ActiveRecord::Base 
 ["/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:564:in `retrieve_connection'", "/var/lib/gems/2.2.0/gems/composite_primary_keys-8.0.0/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:48:in `retrieve_connection'", "/var/lib/gems/2.2.0/gems/composite_primary_keys-8.0.0/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:30:in `connection'", "/var/lib/gems/2.2.0/gems/arel-6.0.0/lib/arel/nodes/node.rb:48:in `to_sql'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:388:in `column_name_for_operation'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:257:in `execute_simple_calculation'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:221:in `perform_calculation'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:127:in `calculate'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:42:in `count'", "/var/lib/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:13:in `count'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/strategy/base.rb:79:in `process'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/core/database.rb:64:in `block in anonymize'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/core/database.rb:62:in `each'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/core/database.rb:62:in `anonymize'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/core/database.rb:46:in `anonymize'", "/var/lib/gems/2.2.0/gems/data-anonymization-0.6.7/lib/core/dsl.rb:10:in `database'", "test.rb:7:in `<main>'"]
```

The strange thing is that when I add this line just after setting log level:
```
ActiveRecord::Base.establish_connection	:adapter => 'mysql', :host => 'localhost', :port => 3306, :pool => 5, :username => 'root', :password => 'mysql', :database => 'test'
```

the script starts to run, but data does not change, there are debug messages like that: 
```
D, [2015-03-03T11:40:38.789798 #14739] DEBUG -- :   SQL (0.1ms)  BEGIN
D, [2015-03-03T11:40:38.798250 #14739] DEBUG -- :   SQL (0.4ms)  UPDATE `user` SET `EMAIL` = ? WHERE `user`.`id` IS NULL  [["EMAIL", "81YK1dWtj@test.com"]]
D, [2015-03-03T11:40:38.798870 #14739] DEBUG -- :    (0.1ms)  COMMIT
```

What should I change to start Blacklist strategy working? Is it a correct way to establish Active Record connection before stating anonymization process? Shouldn't the data-anonymization script establish it?

**Comment by sunitparekh** [comment]
data-anonymization script should establish connection by itself. Since it is using the blacklist strategy it should update the data in database. let me try your example and test it myself. Give me a day and i will get back to you.

**Comment by sunitparekh** [comment]
One quick observation from the log message is UPDATE statement shows `WHERE user.id IS NULL`, that seems little odd to me. Does the primary key field with name `ID` exists in your database table `user`?

**Comment by rpiotrow** [comment]
Yes, That's quite odd, but I already know the answer. The column name in database is 'ID', not 'id'. Database is set to be case-insensitive to column names, but somehow ActiveRecord is not working with that. Funny think is that in script there is column 'email' and in database it is 'EMAIL', but i didn't have to change the script - it updates 'EMAIL' column. Here is final script:
```
require 'data-anonymization'

DataAnon::Utils::Logging.logger.level = Logger::DEBUG

database 'test' do
	strategy DataAnon::Strategy::Blacklist
	source_db :adapter => 'mysql', :host => 'localhost', :port => 3306, :pool => 5, :username => 'root', :password => 'mysql', :database => 'test'

	table 'user' do
		primary_key 'ID'

		anonymize('email').using FieldStrategy::RandomEmail.new('test','com')
	end

end
```

Thank you very much for your help.

**Comment by sunitparekh** [comment]
Good to hear that you are able to proceed. I will try and look into the
case sensitive problem and add it to a quick FAQ or Troubleshooting section
on my documentation to look out for such gotchas.

I hope tool is useful and if you end up using it. Please feel free to share
your feedback or enhancements you would like to do. I am happy to extend
features in tool based on real user feedback. And I added mongodb (NoSQL)
support from such request.

regards,
Sunit.

On Wed, Mar 4, 2015 at 12:56 PM, Rafal Piotrowski <notifications@github.com>
wrote:

> Yes, That's quite odd, but I already know the answer. The column name in
> database is 'ID', not 'id'. Database is set to be case-insensitive to
> column names, but somehow ActiveRecord is not working with that. Funny
> think is that in script there is column 'email' and in database it is
> 'EMAIL', but i didn't have to change the script - it updates 'EMAIL'
> column. Here is final script:
>
> require 'data-anonymization'
>
> DataAnon::Utils::Logging.logger.level = Logger::DEBUG
>
> database 'test' do
>     strategy DataAnon::Strategy::Blacklist
>     source_db :adapter => 'mysql', :host => 'localhost', :port => 3306, :pool => 5, :username => 'root', :password => 'mysql', :database => 'test'
>
>     table 'user' do
>         primary_key 'ID'
>
>         anonymize('email').using FieldStrategy::RandomEmail.new('test','com')
>     end
>
> end
>
> Thank you very much for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunitparekh/data-anonymization/issues/24#issuecomment-77108620>
> .
>



-- 
thanks & regards,
Sunit
parekh.sunit@gmail.com

**Comment by rpiotrow** [comment]
There is one more thing considering this script. I needed to add invocation of establish_connection method before anonymization part. Without it I get still connection errors. Is it the desired way of using data-anonymization?

**Comment by sunitparekh** [comment]
nope. You are not required to add such connection statement before.
Let me try and look into that. let me try and test it with mysql database.

On Wed, Mar 4, 2015 at 3:09 PM, Rafal Piotrowski <notifications@github.com>
wrote:

> There is one more thing considering this script. I needed to add
> invocation of establish_connection method before anonymization part.
> Without it I get still connection errors. Is it the desired way of using
> data-anonymization?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunitparekh/data-anonymization/issues/24#issuecomment-77124520>
> .
>



-- 
thanks & regards,
Sunit
parekh.sunit@gmail.com

**Comment by wpodgorski** [comment]
Any luck checking Sunit?

**Comment by sunitparekh** [comment]
No luck, I am not sure why adding establish connection call required.
Actually if you look at the code of 'data-anonmyzation' line Base class # 73
<https://github.com/sunitparekh/data-anonymization/blob/master/lib/strategy/base.rb#L73>
it has the establish_connection method call.

https://github.com/sunitparekh/data-anonymization/blob/master/lib/strategy/base.rb#L73

I have to dig into why it is behaving odd with mysql database. Give me
sometime.



On Mon, Mar 9, 2015 at 4:25 PM, Wojciech Podgórski <notifications@github.com
> wrote:

> Any luck checking Sunit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunitparekh/data-anonymization/issues/24#issuecomment-77833353>
> .
>



-- 
thanks & regards,
Sunit
parekh.sunit@gmail.com

**Comment by sunitparekh** [comment]
@rpiotrow I have published v0.7.0 and fixed issue with cases in fieldnames. In code for some reason I was doing `downcase` which might be causing issues for you. Please try latest version and now you should not have issues with cases. Make sure case matches with database field name case. 

I am still looking into why you need to add `ActiveRecord::Base.establish_connection` at the beginning.
